[package]
name = "fischl"
description = "Helper library to manage compatibility and downloads for KeqingLauncher"
authors = ["TukanDev"]
version = "0.1.0"
edition = "2024"

[dependencies]
wincompatlib = {version = "0.7.7", features = ["all"], optional = true}

[features]
compat = ["dep:wincompatlib"]

default = []
