[package]
name = "fischl"
description = "Helper library to manage compatibility and downloads for KeqingLauncher"
authors = ["TukanDev"]
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1", features = ["derive"]}
wincompatlib = {version = "0.7.7", features = ["all"], optional = true}
compress-tools = {version = "0.15.1", features = [], optional = true}
reqwest = {version = "0.12.15", features = ["blocking", "json"], optional = true}
md-5 = {version = "0.10", optional = true}
sysinfo = "0.34.2"
serde_json = "1.0.140"
thiserror = "1.0"

[features]
compat = ["dep:wincompatlib"]
download = ["dep:compress-tools", "dep:reqwest", "dep:md-5"]

default = ["download"]
